server:
    port: 8081
    
# MySQL Configuration
spring:
  datasource:
    url: jdbc:mysql://${LOCALHOST}:3306/agile
    username: ${DB_USER}
    password: ${DB_PASSWORD}

    driver-class-name: com.mysql.cj.jdbc.Driver

  # Hibernate Configuration
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
      
# Configure Actuator Endpoints     
management:
  endpoints:
    web:
      exposure:
        include: health
      
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.jdbc.core: DEBUG
